<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Innsending av Min side Form',
	'heading' => 'Ny innsending av skjema',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Avmerket',
		'checkbox_unchecked' => 'Ikke avmerket',
		'submitted_from' => 'Skjema sendt fra webområde: %s',
		'submitted_by' => 'IP-adresse for besøkende: %s',
		'too_many_submissions' => 'For mange nylige innsendinger fra denne IP-adressen',
		'failed_to_send_email' => 'Kan ikke sende e-post',
		'invalid_reCAPTCHA_private_key' => 'Ugyldig reCAPTCHA-privatnøkkel.',
		'invalid_reCAPTCHA2_private_key' => 'Ugyldig reCAPTCHA 2.0-privatnøkkel.',
		'invalid_reCAPTCHA2_server_response' => 'Ugyldig reCAPTCHA 2.0-serverrespons.',
		'invalid_field_type' => 'Ukjent felttype, %s.',
		'invalid_form_config' => 'Feltet %s har en ugyldig konfigurasjon.',
		'unknown_method' => 'Ukjent serverforespørselsmetode'
	),
	'email' => array(
		'from' => 'endre.m.synnes@gmail.com',
		'to' => 'endre.m.synnes@gmail.com'
	),
	'fields' => array(
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-post',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet E-post er obligatorisk.',
				'format' => 'Feltet E-post inneholder en ugyldig e-postadresse.'
			)
		),
		'custom_U1069' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Passord',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Passord er obligatorisk.'
			)
		),
		'custom_U1052' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Bekreft passord',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Bekreft passord er obligatorisk.'
			)
		),
		'custom_U1161' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Navn',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet Navn er obligatorisk.'
			)
		)
	)
);

process_form($form);
?>
