<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.1.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Min side Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'findus1994@gmail.com',
		'to' => 'findus1994@gmail.com'
	),
	'fields' => array(
		'custom_U1910' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Endre navn',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Endre navn\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Endre E-post',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Endre E-post\' is required.',
				'format' => 'Field \'Endre E-post\' has an invalid email.'
			)
		),
		'custom_U1996' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Passord',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Passord\' is required.'
			)
		),
		'custom_U2013' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Bekreft Passord',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Bekreft Passord\' is required.'
			)
		)
	)
);

process_form($form);
?>
